version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5494:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "ecf"
